name: 'Terraform Action'
description: 'Reusable GitHub Action for Terraform operations'

inputs:
  environment:
    description: 'Environment'
    required: true

outputs:
  ecr-app-repo:
    description: 'ECR App Repository URL'
    value: ${{ steps.outputs.outputs.ecr-app-repo }}

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init -update -backend-config="key=state/${{ inputs.environment }}/terraform.tfstate"
      shell: bash
      working-directory: './infra'

    - name: Terraform Format
      run: terraform fmt
      shell: bash
      working-directory: './infra'

    - name: Terraform Plan
      run: terraform plan -input=false
      shell: bash
      working-directory: './infra'

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false -target="module.ecr"
      shell: bash
      working-directory: './infra'

    - name: Set Outputs
      id: outputs
      run: |
        echo "ecr-app-repo=$(terraform output -json ecr_repo | jq -r .ecr_repository_1)" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: './infra'


