name: CI-CD Pipeline

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment (dev, uat, prod)'
        required: true
        type: string
        default: 'dev'
      aws-region:
        description: 'AWS Region'
        required: false
        type: string
        default: 'us-east-1'

    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  # CI Pipeline
  ci-pipeline:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1 
        with:
          mask-password: true

      - name: Build and Push App Image to ECR
        id: app-image
        uses: ./.github/actions/ecr
        with:
          ecr-repo: "863700943489.dkr.ecr.us-east-1.amazonaws.com/cicd-lab-app-repo"
          working-directory: './Project_Group3'

    outputs:
      app-image: ${{ steps.app-image.outputs.image }}

# CD Pipeline 
  cd-pipeline:
    needs: ci-pipeline
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Update Dockerrun.aws.json with commit SHA
        run: |
          jq --arg tag "$GITHUB_SHA" '
            .Image.Name = (.Image.Name + ":" + $tag)
          ' Dockerrun.aws.json > tmp.json && mv tmp.json Dockerrun.aws.json
        working-directory: '.'
      
      - name: Update Beanstalkon configuration with commit SHA
        run: |
          zip deployment.zip Dockerrun.aws.json
          aws s3 cp deployment.zip s3://chienpq137-863700943489-us-east-1-an/deployment.zip
          
          aws elasticbeanstalk create-application-version \
            --application-name PRN222 \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket="chienpq137-863700943489-us-east-1-an",S3Key="deployment.zip"

          aws elasticbeanstalk update-environment \
            --environment-name PRN222-env-1 \
            --version-label $GITHUB_SHA
        working-directory: '.'