name: CI-CD Pipeline

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment (dev, uat, prod)'
        required: true
        type: string
        default: 'dev'
      aws-region:
        description: 'AWS Region'
        required: false
        type: string
        default: 'us-east-1'

    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  # CI Pipeline
  ci-pipeline:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Module ECR
        id: ecr-repo
        uses: ./.github/actions/terraform_ecr
        with:
          environment: ${{ inputs.environment }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1 
        with:
          mask-password: true

      - name: Build and Push App Image to ECR
        id: app-image
        uses: ./.github/actions/ecr
        with:
          ecr-repo: ${{ steps.ecr-repo.outputs.ecr-app-repo }}
          working-directory: './Project_Group3'

    outputs:
      app-image: ${{ steps.app-image.outputs.image }}

# CD Pipeline 
  cd-pipeline:
    needs: ci-pipeline
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Module ECS
        id: terraform-ecs
        uses: ./.github/actions/terraform_ecs
        with:
          environment: ${{ inputs.environment }}

      - name: Deploy App to ECS
        uses: ./.github/actions/ecs
        with:
          cluster-name: ${{ steps.terraform-ecs.outputs.cluster-name }}
          service: ${{ steps.terraform-ecs.outputs.app }}
          image: ${{ needs.ci-pipeline.outputs.app-image }}
